BlogWeb/Controllers/AuthController.cs
using AutoMapper;
using BlogUtility;
using BlogWeb.Models;
using BlogWeb.Models.Dto;
using BlogWeb.Services.IServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace BlogWeb.Controllers
{
	public class AuthController : Controller
	{
		private readonly IUserService _userService;
		private readonly IAuthService _authService;
		private readonly IMapper _mapper;
		private readonly IHttpContextAccessor _httpContextAccessor;
		private readonly string _token;
		public AuthController(IUserService userService, IMapper mapper, IAuthService authService, IHttpContextAccessor httpContextAccessor)
		{
			_userService = userService;
			_mapper = mapper;
			_authService = authService;
			_httpContextAccessor = httpContextAccessor;
			_token = _httpContextAccessor.HttpContext?.Request.Cookies["AuthToken"];
		}



		[HttpGet]
		[Route("Register")]
		public IActionResult Register()
		{
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
		}

		[HttpPost]
		[Route("Register")]
		public async Task<IActionResult> Register(UserCreateDTO userDTO)
		{
			var chcekEmailResponse = await IsEmailAvailable(userDTO.Email) as JsonResult;
            bool isEmailAvailable = (bool)chcekEmailResponse.Value;
			if (isEmailAvailable) {
				ModelState.AddModelError("Email", "Email already exists!");
			}

			var chcekUsernameResponse = await IsUsernameAvailable(userDTO.UserName) as JsonResult;
			bool isUsernameAvailable = (bool)chcekUsernameResponse.Value;
			if (isUsernameAvailable)
			{
				ModelState.AddModelError("UserName", "Username already exists!");
			}

			if (ModelState.IsValid)
			{
				var response = await _userService.CreateAsync<APIResponse>(userDTO);
				if (response != null && response.IsSuccess) {
					TempData["success"] = "Your account has been created!";
					return RedirectToAction(nameof(Login));
				}
			}
			//TempData["error"] = "Something went wrong!";
			return View(userDTO);

		}


		[HttpGet]
		[Route("Login")]
		public IActionResult Login()
		{
			if (User.Identity.IsAuthenticated) { 
				return RedirectToAction("Index", "Home");
			}

			return View();
		}

		[HttpPost]
		[Route("Login")]
		public async Task<IActionResult> Login(LoginRequestDTO loginDTO)
		{
			if (!ModelState.IsValid) { 
				return View(loginDTO);
			}
			APIResponse response = await _authService.LoginAsync<APIResponse>(loginDTO);
			if (response != null && response.IsSuccess)
			{
				LoginResponseDTO model = JsonConvert.DeserializeObject<LoginResponseDTO>(Convert.ToString(response.Result));	
				var handler = new JwtSecurityTokenHandler();
				var jwt = handler.ReadJwtToken(model.Token);
				var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
				identity.AddClaim(new Claim(ClaimTypes.Email, jwt.Claims.FirstOrDefault(u=>u.Type == "email").Value));
				identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(u=>u.Type == "role").Value));
				var principle = new ClaimsPrincipal(identity);
				await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principle);

				// Store Token in session
				//HttpContext.Session.SetString(SD.SessionToken, model.Token);
				//var token = HttpContext.Session.GetString(SD.SessionToken);

				// Store Token in cookie
				var cookieOptions = new CookieOptions
				{
					HttpOnly = true, // Prevent JavaScript access (XSS protection)
					Secure = true,   // Only transmit over HTTPS
					SameSite = SameSiteMode.Strict, // Prevent CSRF attacks
					Expires = DateTime.UtcNow.AddMinutes(60) // Expiry time
				};

				Response.Cookies.Append("AuthToken", model.Token, cookieOptions);

				return RedirectToAction("Index", "Home");
			}
			else
			{
				ModelState.AddModelError("CustomError", response.ErrorMessages.FirstOrDefault());
				TempData["error"] = "Username or password is incorrect!";
				return View(loginDTO);
			}

		}


		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync();
			//Using Session
			//HttpContext.Session.SetString(SD.SessionToken, "");

			// Using Cookie
			Response.Cookies.Delete("AuthToken");
			return RedirectToAction("Index", "Home");
		}

		[Route("AccessDenied")]
		public IActionResult AccessDenied()
		{
			return View();
		}




		//Unique email check for Remote validation
		[HttpGet]
		public async Task<IActionResult> IsEmailAvailable(string email)
		{
			var response = await _userService.GetAllAsync<APIResponse>();
			var users = JsonConvert.DeserializeObject<List<UserDTO>>(Convert.ToString(response.Result));
			bool result;
			if (users != null) {
				foreach (var user in users)
				{
					if (user.Email == email)
					{
						result = true;
						return Json(result);
					}
				}
			}
			result = false;
            return Json(result);
        }

		//Unique username check for Remote validation
		[HttpGet]
		public async Task<IActionResult> IsUsernameAvailable(string username)
		{
			var response = await _userService.GetAllAsync<APIResponse>();
			var users = JsonConvert.DeserializeObject<List<UserDTO>>(Convert.ToString(response.Result));
			bool result;
			if (users != null)
			{
				foreach (var user in users)
				{
					if (user.UserName == username)
					{
						result = true;
						return Json(result);
					}
				}
			}
			result = false;
			return Json(result);
		}

	}
}

BlogWeb/Controllers/PostController.cs
using BlogWeb.Models;
using BlogWeb.Models.Dto;
using BlogWeb.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BlogWeb.Controllers
{
    public class PostController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICategoryService _categoryService;
        private readonly IPostService _postService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly string _token;
        private readonly string _baseUrl;

        public PostController(ILogger<HomeController> logger, IConfiguration configuration, ICategoryService categoryService, IPostService postService, IHttpContextAccessor httpContextAccessor)
        {
            _logger = logger;
            _baseUrl = configuration.GetValue<string>("ServiceUrls:BlogAPI");
            _categoryService = categoryService;
            _postService = postService;
            _httpContextAccessor = httpContextAccessor;
            _token = _httpContextAccessor.HttpContext?.Request.Cookies["AuthToken"];
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Article(int id)
        {

            var postResponse = await _postService.GetAsync<APIResponse>(id);
            var post = JsonConvert.DeserializeObject<PostDTO>(Convert.ToString(postResponse.Result));
            ViewBag.Post = post;
            return View();

        }

        public async Task<IActionResult> Search(string input)
        {
            var postsResponse = await _postService.GetAllAsync<APIResponse>();
            var posts = JsonConvert.DeserializeObject<List<PostDTO>>(Convert.ToString(postsResponse.Result));
            var searchResult = posts.Where(p => p.Title.Contains(input, StringComparison.OrdinalIgnoreCase)
                                        || p.Content.Contains(input, StringComparison.OrdinalIgnoreCase)).ToList();

            ViewBag.Posts = searchResult;

            return View();


        }
    }
}

BlogWeb/ViewComponents/CategoryMenuViewComponent.cs
using BlogWeb.Models;
using BlogWeb.Models.Dto;
using BlogWeb.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NuGet.Common;

namespace BlogWeb.ViewComponents
{
	public class CategoryMenuViewComponent : ViewComponent
	{
		private readonly ICategoryService _categoryService;
		private readonly IHttpContextAccessor _httpContextAccessor;
		public CategoryMenuViewComponent(ICategoryService categoryService, IHttpContextAccessor httpContextAccessor)
		{
			_categoryService = categoryService;
			_httpContextAccessor = httpContextAccessor;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var response = await _categoryService.GetAllAsync<APIResponse>();
			var categories = JsonConvert.DeserializeObject<List<CategoryDTO>>(Convert.ToString(response.Result));
			return View(categories);
		}
	}
}

BlogWeb/ViewComponents/LatestArticlesViewComponent.cs
using BlogWeb.Models;
using BlogWeb.Models.Dto;
using BlogWeb.Models.VM;
using BlogWeb.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BlogWeb.ViewComponents
{
    public class LatestArticlesViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;
        private readonly IPostService _postService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly string _token;
        private readonly string _baseUrl;
        public LatestArticlesViewComponent(IConfiguration configuration ,ICategoryService categoryService, IPostService postService, IHttpContextAccessor httpContextAccessor)
        {
            _baseUrl = configuration.GetValue<string>("ServiceUrls:BlogAPI");
            _categoryService = categoryService;
            _postService = postService;
            _httpContextAccessor = httpContextAccessor;
            _token = _httpContextAccessor.HttpContext?.Request.Cookies["AuthToken"];
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categoryResponse = await _categoryService.GetAllAsync<APIResponse>();
            var categories = JsonConvert.DeserializeObject<List<CategoryDTO>>(Convert.ToString(categoryResponse.Result));

            var postResponse = await _postService.GetAllAsync<APIResponse>();
            var posts = JsonConvert.DeserializeObject<List<PostDTO>>(Convert.ToString(postResponse.Result));

            var latestOne = posts.OrderByDescending(p => p.Id).FirstOrDefault();
            var latestPosts = posts.OrderByDescending(p => p.Id).Take(5).ToList();

            ViewData["latestOne"] = latestOne;
            ViewData["latestPosts"] = latestPosts;
            ViewData["baseUrl"] = _baseUrl;

            return View();
        }
    }
}

BlogWeb/Views/Shared/_Footer.cshtml
<footer class="bg-dark mt-5">
    <div class="container section">
        <div class="row">
            <div class="col-lg-10 mx-auto text-center">
                <a class="d-inline-block mb-4 pb-2" href="#">
                    <img loading="prelaod" decoding="async" class="img-fluid" src="~/theme/images/logo-white.png" alt="Reporter Hugo">
                </a>
                <ul class="p-0 d-flex navbar-footer mb-0 list-unstyled">
                    <li class="nav-item my-0"> <a class="nav-link" asp-controller="Home" asp-action="About">About</a></li>
                    <li class="nav-item my-0"> <a class="nav-link" asp-controller="Home" asp-action="PrivacyPolicy">Privacy Policy</a></li>
                    <li class="nav-item my-0"> <a class="nav-link" asp-controller="Home" asp-action="TermsConditions">Terms Conditions</a></li>
                    <li class="nav-item my-0"> <a class="nav-link" asp-controller="Home" asp-action="Page404">404 Page</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="copyright bg-dark content">&copy; @DateTime.Now.Year Sudan Blog. All Rights Reserved.</a></div>
</footer>

BlogWeb/Views/Shared/_Header.cshtml
@using BlogUtility
@model BlogWeb.Models.Dto.CategoryDTO;
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc
<header class="navigation">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light px-0">
            <a class="navbar-brand order-1 py-0" href="#">
                <img loading="prelaod" decoding="async" class="img-fluid" src="~/theme/images/logo.png" alt="Reporter Hugo">
            </a>
            <div class="navbar-actions order-3 ml-0 ml-md-4">
                <button aria-label="navbar toggler" class="navbar-toggler border-0" type="button" data-toggle="collapse"
                        data-target="#navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <form asp-controller="Post" asp-action="Search" class="search order-lg-3 order-md-2 order-3 ml-auto">
                <input id="search-query" name="input" type="search" placeholder="Search..." autocomplete="off">
            </form>
            <div class="collapse navbar-collapse text-center order-lg-2 order-4" id="navigation">
                <ul class="navbar-nav mx-auto mt-3 mt-lg-0">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Auth" asp-action="Logout">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Management" asp-controller="Post" asp-action="Index" target="_blank">Management</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                    }
                    <li class="nav-item dropdown">
                        @await Component.InvokeAsync("CategoryMenu")
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>

BlogWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogWeb.styles.css" asp-append-version="true" />

    <!-- theme meta -->
    <meta name="theme-name" content="reporter" />

    <!-- # Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Neuton:wght@700&family=Work+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- # CSS Plugins -->
    <link rel="stylesheet" href="~/theme/plugins/bootstrap/bootstrap.min.css">

    <!-- # Main Style Sheet -->
    <link rel="stylesheet" href="~/theme/css/style.css">
</head>
<body>
    <partial name="_Notification" />
    <partial name="_Header" />
    <main>
        <section class="section">
            <div class="container">               
                <div class="row no-gutters-lg">
                    @RenderBody()
                    <div class="col-lg-4">
                        <partial name="_Widget" />
                    </div>
                </div>
            </div>
        </section>
    </main>

    <partial name="_Footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- # JS Plugins -->
    <script src="~/theme/plugins/jquery/jquery.min.js"></script>
    <script src="~/theme/plugins/bootstrap/bootstrap.min.js"></script>

    <!-- Main Script -->
    <script src="~/theme/js/script.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogWeb/Views/Shared/_Notification.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@if (TempData["success"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
    </script>
}
@if (TempData["error"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
    </script>
}
@if (TempData["warning"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'warning',
            title: '@TempData["warning"]',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        })
    </script>
}

BlogWeb/Views/Shared/_StaticLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogWeb.styles.css" asp-append-version="true" />

    <!-- theme meta -->
    <meta name="theme-name" content="reporter" />

    <!-- # Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Neuton:wght@700&family=Work+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- # CSS Plugins -->
    <link rel="stylesheet" href="~/theme/plugins/bootstrap/bootstrap.min.css">

    <!-- # Main Style Sheet -->
    <link rel="stylesheet" href="~/theme/css/style.css">
</head>
<body>

    <partial name="_Header" />
    <main>
        <section class="section">
            <div class="container">
                <div class="row no-gutters-lg">
                    @RenderBody()
                </div>
            </div>
        </section>
    </main>

    <partial name="_Footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- # JS Plugins -->
    <script src="~/theme/plugins/jquery/jquery.min.js"></script>
    <script src="~/theme/plugins/bootstrap/bootstrap.min.js"></script>

    <!-- Main Script -->
    <script src="~/theme/js/script.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogWeb/Views/Shared/_Widget.cshtml
<div class="widget-blocks">
    <div class="row">
        <div class="col-lg-12 col-md-6">
            <div class="widget">
                <h2 class="section-title mb-3">Recommended</h2>
                <div class="widget-body">
                    <div class="widget-list">
                        @await Component.InvokeAsync("LatestArticles")
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-6">
            <div class="widget">
                <h2 class="section-title mb-3">Categories</h2>
                <div class="widget-body">
                    <ul class="widget-list">
                        @await Component.InvokeAsync("CategoryWithCount")
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>